"""milestone10_full_phase_b_c_d

Revision ID: 761b1c5d91e8
Revises: c3d4e5f6a7b8
Create Date: 2026-07-24 10:54:06.080547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761b1c5d91e8'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_widget_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_created_at'), 'event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_event_id'), 'event_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_organization_id'), 'event_logs', ['organization_id'], unique=False)
    op.create_table('incoming_webhook_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_webhook_keys_key_hash'), 'incoming_webhook_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_incoming_webhook_keys_organization_id'), 'incoming_webhook_keys', ['organization_id'], unique=False)
    op.create_table('outgoing_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outgoing_webhooks_organization_id'), 'outgoing_webhooks', ['organization_id'], unique=False)
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'retrying', name='webhook_delivery_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['outgoing_webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_organization_id'), 'webhook_delivery_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_webhook_id'), 'webhook_delivery_logs', ['webhook_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'converted', name='chat_conversation_status'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['chat_visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_organization_id'), 'chat_conversations', ['organization_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('visitor', 'agent', 'system', name='chat_sender_type'), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('email_attachments_comment_id_fkey'), 'email_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'email_attachments', 'ticket_comments', ['comment_id'], ['id'])
    op.alter_column('tickets', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('workflow_actions_rule_id_fkey'), 'workflow_actions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_actions', 'workflow_rules', ['rule_id'], ['id'])
    op.drop_constraint(op.f('workflow_conditions_rule_id_fkey'), 'workflow_conditions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_conditions', 'workflow_rules', ['rule_id'], ['id'])
    op.drop_constraint(op.f('workflow_execution_logs_ticket_id_fkey'), 'workflow_execution_logs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_execution_logs_rule_id_fkey'), 'workflow_execution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_execution_logs', 'workflow_rules', ['rule_id'], ['id'])
    op.create_foreign_key(None, 'workflow_execution_logs', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_execution_logs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_execution_logs', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_execution_logs_rule_id_fkey'), 'workflow_execution_logs', 'workflow_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_execution_logs_ticket_id_fkey'), 'workflow_execution_logs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'workflow_conditions', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_conditions_rule_id_fkey'), 'workflow_conditions', 'workflow_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'workflow_actions', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_actions_rule_id_fkey'), 'workflow_actions', 'workflow_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.alter_column('tickets', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'email_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('email_attachments_comment_id_fkey'), 'email_attachments', 'ticket_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_conversations_organization_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_webhook_delivery_logs_webhook_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_organization_id'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_index(op.f('ix_outgoing_webhooks_organization_id'), table_name='outgoing_webhooks')
    op.drop_table('outgoing_webhooks')
    op.drop_index(op.f('ix_incoming_webhook_keys_organization_id'), table_name='incoming_webhook_keys')
    op.drop_index(op.f('ix_incoming_webhook_keys_key_hash'), table_name='incoming_webhook_keys')
    op.drop_table('incoming_webhook_keys')
    op.drop_index(op.f('ix_event_logs_organization_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_created_at'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('chat_widget_settings')
    op.drop_table('chat_visitors')
    # ### end Alembic commands ###
